### ISSUE TITLE
Feedback on standard

### ISSUE THREAD

**Issue by HarryR** [EYBlockchain/zksnark-verifier-standard#1]
So, the API in the doc can be condensed down to:
```solidity
function setPublicInputVectorLength(uint _length, uint256 _proofId) public;
function loadPublicInputVector(uint[] _input, uint _start, uint256 _proofId) public;
function setProofLength(uint _length, uint256 _proofId) public;
function loadProof(uint[][] _proof, uint256 _proofId) public;
function setVerifyingKeyLength(uint _length, uint256 _vkId) public;
function loadVerifyingKeyPart1(uint[][] _vk, uint256 _vkId) public;
function loadVerifyingKeyPart2(uint[][] _points, uint _start, uint256 _vkId) public;
function computeVkx(uint _start, uint _end, uint256 _vkId) public;
function verifyProof(uint256 _proofId, uint256 _vkId) internal returns (uint);
function verify(uint256 _proofID, uint256 _vkId) public returns (bool);
function getAddress() public returns(address);
function getNewProofId() returns (uint256);
function getProof(_proofID) public returns (uint[][]);
function getNewVkId() returns (uint256);
function getVerifyingKey(_vkID) public returns (uint[][]);
event Verified(bool indexed _verified);
```

At a high level, it seems like there is no simple public interface, other than the ERC-165 meta-interface, it looks like the guts of the implementation details *are the interface*, and any program which uses this interface will be tightly coupled with this one implementation and the semantics of its limitations.

Another problem, is the asynchronous nature of calls, it turns something that should take 1 call into something that takes 5 or 6. Where the non-trivial protocol of interacting with the tightly-coupled implementation is pushed up to the caller, and the caller must know (and hard-code) implementation-specific details such as the proof length.

A lot of this seems to stem from the number of public inputs being too big to be handled by a single call, e.g.

```
/// Note: some of the below functions are only required as a result of
/// limitations of the EVM. Limitations include:
/// - Block gas limit.
/// - Limited stack space for functions' local variables.
```

These aren't problems with EVM, they're deficiencies in the implementation that could be worked around. If the number of public inputs are too large for it to be processed within a single block, then you have no hope of processing anything on the public blockchain. Almost every protocol can be condensed into 1 or 2 public inputs, using hashing to verify the on-chain contract and circuit are working on the same data, anything more is cost prohibitive.

Do you have any example of how an application would use this interface? It would be interesting to simplify it, hiding all of the implementation and algorithm-specific details from the caller with a little overhead as possible, as I have done with: https://github.com/Zoffee/zoffee-onchain

There are also some oddities, such as:

    function getAddress() public returns(address);

If you're calling the contract, surely you know what it's address is? It's like having `void* getThis() { return (void*)this; }`...

**Comment by HarryR** [comment]
So, lets split this into multiple interfaces:

  1) For applications which need to verify zkSNARK proofs
  2) For implementations of zkSNARK proof verification algorithms
  3) EY specific stuff and implementation details

For Zoffee I made some assumptions that work well for when the application and the verification are disconnected from each other - that is somebody interacts with one contract to perform the verification, then submits a limited amount of information (mostly hashes) to another contract which confirms whether or not it's valid. However, that requires an extra call, and ideally should work using only a single call.

Lets start with the zkSNARK verification algorithm interface:

```solidity
interface ProofAlgorithm
{
    /**
    * Check whether or not a proving key is valid and can be used to verify proofs
    */
    function IsValidationKeyValid( uint256[] key_data ) external returns (bool);

    /**
    * Check if the proof data is valid for a specific validation key
    */
    function IsProofValid( uint256[] key_data, uint256[] proof_data, uint256[] inputs ) external returns (bool);
}
```

The `key_data` parameter contains the verification key, and `proof` the algorithm-agnostic proof, the types of both could be changed to `uint[][]` to make it easier in some ways (e.g. if there are multiple elements of varying sizes, then you get meta-data for free about the length of each part).

The whole key, and all the proof data, and all the inputs, are passed to the algorithms implementation in one call. The implementation doesn't need any persistent state, and all information necessary to verify the proof and inputs are passed as arguments. A separate method exists to verify if the form of a verification key is valid for that algorithm.

This addresses one deficiency in the EY proposed standard: **pluggable algorithms to allow for upgrades without the interface changing**.

How does an application verify a proof? It calls a contract which implements the following interface:

```solidity
interface VerifierInterface
{
    function IsProofValid( bytes32 vk, uint256[] proof_data, uint256[] inputs ) external returns (bool);
}
```

The `vk` parameter identifies a specific verification key, this would be managed by the specific application, it may be hard-coded, or could allow any one from a short whitelist. Verification keys must have previously been registered with the Verifier contract and are associated with a `ProofAlgorithm` instance. From the `vk` parameter the underlying implementation can load the appropriate verification key then pass the `proof_data` and `inputs` parameters to the `ProofAlgorithm` instance.

There is no need to emit an event upon proof validation, what to do upon successful (or unsuccessful) proof validation is determined by the application which requires the proofs.

The above `VerifierInterface` differs compared to the Zoffee repository in that below only the GUID of the proof data and a hash of the inputs are passed to the application, this choice was made because verification of proofs is done in a two-stage process and the call to the application doesn't need to duplicate the proof data or inputs - it only needs hashes of them to confirm if the proof was valid.

```solidity
interface Zoffee_VerifierInterface
{
    function IsProofValid( bytes32 vk, bytes32 guid, bytes32 inputs_hash ) external returns (bool);
}
```

The interface for registering verification keys is:

```solidity
contract VerifierRegistryInterface is VerifierInterface
{
    /**
    * Register a verifier type, this is a contract which can be used to validate a verification key
    * and then validate a proof for a specific verification key.
    *
    * emits OnVerifierRegistered
    *
    * @param verifier Implements the `ProofAlgorithm` interface
    */
    function RegisterVerifier( ProofAlgorithm verifier ) public;


    /**
    * Register a key to be used for verification
    *
    * It is associated with a verifier, which will be used to validate the `key_data`.
    * The `verifier` contract must have been previously registered.
    * The `key_data` is validated by calling `verifier.IsValidationKeyValid()`
    *
    * emits OnKeyRegistered
    *
    * @param verifier Contract used to verify the proofs
    * @param key_data Auxilliary data used by the verifier to validate proofs
    * @return Hash to be used as `vk` parameter when calling `VerifierInterface`
    */
    function RegisterKey( ProofAlgorithm verifier, uint256[] key_data ) public returns (bytes32);
}
```

There can be multiple `ProofAlgorithm` instances registered, and verification keys can use any of the registered verifiers. Verification keys are referenced by applications by using a `bytes32` identifier.

The main design choice that EY made which seems to have significantly influenced the design of the EY interface is to allow loading the verification key and proof inputs in multiple parts. I think this is a very bad decision and overly complicates what could be a simple interface because if any verification key or proof inputs are too big to be loaded in a single block, then it's impossible that any proof could be verified in a single block.

Using `computeVkx` to compute chunks of the verification key to spread the load across multiple blocks, while I can see it's a necessity if you have a *large* number of inputs - it is unnecessary. You should not be passing any more than a handful of inputs between EVM and the circuit, the overhead is too much. Instead you should be hashing data on EVM, passing the hash of the data, then pass the data as private inputs to the circuit and verify the hash matches. The interface should not be over-complicated to work for circuits with a large number of inputs so it does not promote bad practices and highly inefficient choices.

The proposed EY interface doesn't account for different multiple algorithms, or adding new proving systems at a later date, but the interface I propose above does.

**Comment by MichaelConnorOfficial** [comment]
Many thanks for all of your suggestions @HarryR.

I've made some major updates to the Verifier standard proposal, and have written an accompanying Verifier Registry standard proposal.

I'll close this issue.
