### ISSUE TITLE
Remove `node_modules` directory from `implementation`

### ISSUE THREAD

**Issue by HarryR** [EYBlockchain/zksnark-verifier-standard#4]
It is unnecessary to include over a million lines of third-party source code in the repository.

Please remove `node_modules` and add it to `.gitignore` in the `implementation` directory.

Using a `package-lock.json` file is sufficient for everybody, it is a package manager, it does its thing without spamming up the git repo.

**Comment by MichaelConnorOfficial** [comment]
Whoops, thanks Harry, I’ll update next week!

**Comment by HarryR** [comment]
Thanks.

Ya give me a couple of days to put some decent feedback together, am trying to make it coherent and well reasoned, but also realistic.
